kind: Service
apiVersion: v1
metadata:
  name: openvino-model-server
spec:
  ports:
#    - port: 8080
#      protocol: TCP
#      targetPort: 8080
#      name: grpc
    - port: 80
      protocol: TCP
      targetPort: 80
      name: rest
  selector:
    app: ovms
  type: ClusterIP
