apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: openvino-model-server-vs
spec:
  gateways:
  - public-gateway.istio-system.svc.cluster.local
  hosts:
  - 'openvino.c360-platform.ninja'
  http:
    - match:
      - port: 8081
      route:
      - destination:
          host: openvino-model-server.msu-workflow-dev.svc.cluster.local
          port:
            number: 8081
    - match:
      - port: 8080
      route:
        - destination:
            host: openvino-model-server.msu-workflow-dev.svc.cluster.local
            port:
              number: 8080
